steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/vanguard-services:$SHORT_SHA'
  - '-t'
  - 'gcr.io/$PROJECT_ID/vanguard-services:master'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: PushSha
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/vanguard-services:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  id: PushMaster
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/vanguard-services:master'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
  - 'deployment/vanguard-k8s.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=vanguard'
