---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanguard-services
  labels:
    app: vanguard-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vanguard-services
  template:
    metadata:
      labels:
        app: vanguard-services
    spec:
      containers:
      - name: vanguard-services
        image: gcr.io/vanguard-255823/vanguard-services:master
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /__health
            port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: vanguard-services
spec:
  type: NodePort
  selector:
    app: vanguard-services
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vanguard-services
spec:
  backend:
    serviceName: vanguard-services
    servicePort: 3000
